"""
@author: wtk
"""
# Import Stuff
import openvsp as vsp

# Setup Vehicle ------------------------------------------------------------------------------------
print("\tSetting vehicle parameters.")
vsp.ClearVSPModel()
# Setup Pod
pod_id = vsp.AddGeom("POD", "")
vsp.SetParmVal(pod_id, "FineRatio", "Design", 20)
wing_id = vsp.AddGeom("WING", pod_id)
#   Param for NACA 4 Series Airfoil
vsp.SetParmVal(wing_id, "ThickChord", "XSecCurve_0", .1) #Range of 0 to 1
vsp.SetParmVal(wing_id, "Camber", "XSecCurve_0", .0) #Range of 0 to 0.09
vsp.SetParmVal(wing_id, "CamberLoc", "XSecCurve_0", .2) #Range of 0.1 to 0.9
#   Param for Wing
vsp.SetParmVal(wing_id, "TotalChord", "WingGeom", 1.9)
#vsp.SetParmVal(wing_id, "Root_Chord", "XSec_1", 1.9)
#vsp.SetParmVal(wing_id, "Tip_Chord", "XSec_1", 1.9)
vsp.SetParmVal(wing_id, "TotalSpan", "WingGeom", 13.5)
#vsp.SetParmVal(wing_id, "Sweep", "XSec_1", 10 ) #Range of -89 to 89
vsp.SetParmVal(wing_id, "Twist", "XSec_0", 0) #Angle of Incidence
vsp.SetParmVal(wing_id, "X_Rel_Location", "XForm", 2.5) #Range of 0 to 10-Chord
#   Params for Accuracy
vsp.SetParmVal(wing_id, "SectTess_U", "XSec_1", 12) #Number of spanwise sections
#vsp.SetParmVal(wing_id, "Density", "Mass_Props", 1)
elev_id = vsp.AddGeom("WING", pod_id)
vsp.SetParmVal(elev_id, "X_Rel_Location", "XForm", 8)
vsp.SetParmVal(elev_id, "TotalArea", "WingGeom", 5)
vsp.SetParmVal(elev_id, "SectTess_U", "XSec_1", 12)
rudd_id = vsp.AddGeom("WING", pod_id)
vsp.SetParmVal(rudd_id, "Sym_Planar_Flag", "Sym", 0.0 ) #Make it not symmetic (just half an airfoil)
vsp.SetParmVal(rudd_id, "X_Rel_Rotation", "XForm", 90) #Rotate it vertically 
vsp.SetParmVal(rudd_id, "X_Rel_Location", "XForm", 8.2)
vsp.SetParmVal(rudd_id, "TotalArea", "WingGeom", 1.5)
vsp.SetParmVal(rudd_id, "SectTess_U", "XSec_1", 12)
vsp.Update()

# Setup and Run Aerodynamic Analysis ---------------------------------------------------------------
# Setup an Aero Analysis (Compute Geometry)
compgeom_name = "VSPAEROComputeGeometry"
print("\tStarting:", compgeom_name)
# Set defaults
vsp.SetAnalysisInputDefaults(compgeom_name)
# Analysis method
analysis_method = list(vsp.GetIntAnalysisInput(compgeom_name, "AnalysisMethod"))
analysis_method[0] = vsp.VORTEX_LATTICE
vsp.SetIntAnalysisInput(compgeom_name, "AnalysisMethod", analysis_method)
# list inputs, type, and current values
#vsp.PrintAnalysisInputs(compgeom_name)
# Execute
print("\t\tExecuting...", end="")
compgeom_resid = vsp.ExecAnalysis(compgeom_name)
print("COMPLETE")
# Get & Display Results
#vsp.PrintResults(compgeom_resid)
# Run the Aerodynamic Analysis (VSPAero Sweep)
analysis_name = "VSPAEROSweep"
vsp.SetAnalysisInputDefaults(analysis_name)
#// Reference geometry set
geom_set = []
geom_set.append(0)
vsp.SetIntAnalysisInput(analysis_name, "GeomSet", geom_set, 0)
ref_flag = []
ref_flag.append(1)
vsp.SetIntAnalysisInput(analysis_name, "RefFlag", ref_flag, 0)
#TODO
wid = wing_id#vsp.FindGeomsWithName("WingGeom")
vsp.SetStringAnalysisInput(analysis_name, "WingID", wid, 0)
#// Freestream Parameters
alpha = []
alpha.append(1.0)
vsp.SetDoubleAnalysisInput(analysis_name, "AlphaStart", alpha, 0)
AlphaNpts = []
vsp.SetIntAnalysisInput(analysis_name, "AlphaNpts", AlphaNpts, 0)
mach = []
mach.append(0.1)
vsp.SetDoubleAnalysisInput(analysis_name, "MachStart", mach, 0)
vsp.Update()
#// list inputs, type, and current values
vsp.PrintAnalysisInputs(analysis_name)
print("")
#// Execute
print("\tExecuting...")
rid = vsp.ExecAnalysis(analysis_name)
print("COMPLETE")
#// Get & Display Results
#vsp.PrintResults( rid )
history_res = vsp.FindLatestResultsID("VSPAERO_History")
load_res = vsp.FindLatestResultsID("VSPAERO_Load")
CL = vsp.GetDoubleResults(history_res, "CL", 0)
cl = vsp.GetDoubleResults(load_res, "cl", 0)
# ADDED TO CREATE A CSV FILE WITH NEEDED INFO
vsp.WriteResultsCSVFile(rid, "z.csv")

# Save and Export Vehicle --------------------------------------------------------------------------
# Update the vehicle before saving/exporting
vsp.Update()
# Save to a file
fname = "test_vehicle.vsp3"
vsp.SetVSP3FileName(fname)
print("\tSaving vehicle file to: ", fname)
vsp.WriteVSPFile(vsp.GetVSPFileName(), vsp.SET_ALL)
# Export STL
fname = "test_vehicle_mesh.stl"
print("\tExporting mesh (STL) as:", fname)
mesh_id = vsp.ExportFile(fname, vsp.SET_ALL, vsp.EXPORT_STL)
vsp.DeleteGeom(mesh_id) # Delete the mesh generated by the STL export

import csv

row = 17; col = 4
with open("z.csv") as f:
    reader = csv.reader(f)
    for i in range(row):
        row = next(reader)
    value = row[col-1]
print(value)

row = 28; col = 4
with open("z.csv") as f:
    reader = csv.reader(f)
    for i in range(row):
        row = next(reader)
    value = row[col-1]  # because python index starts at zero
print(value)