# https://openvsp.org/
#   conda activate vsppytools
#   conda deactivate vsppytools
#   https://openvsp.org/api_docs/latest/
#   Parms are hard, view in vsp3 file or drag from GUI to txt editor
#   Analysis and Results Manager to visualize results

# https://radarsimx.com/radarsimx/radarsimpy/

import openvsp as vsp
fuse = vsp.AddGeom("FUSELAGE")
wing = vsp.AddGeom("WING")



# Save the file
fname = "example_fuse.vsp3"
vsp.SetVSP3FileName(fname)
vsp.Update()
print("\tSaving vehicle file to: ")
print(fname)
vsp.WriteVSPFile(vsp.GetVSPFileName(), vsp.SET_ALL)

mesh_id = vsp.ExportFile("Example_Mesh.stl", vsp.SET_ALL, vsp.EXPORT_STL)
vsp.DeleteGeom(mesh_id) # Delete the mesh generated by the GMSH export
