# https://openvsp.org/
#   conda activate vsppytools
#   conda deactivate vsppytools
#   https://openvsp.org/api_docs/latest/
#   Parms are hard, view in vsp3 file or drag from GUI to txt editor
#   Analysis and Results Manager to visualize results

# https://radarsimx.com/radarsimx/radarsimpy/

import openvsp as vsp

#fuse_id = vsp.AddGeom("FUSELAGE")
pod_id = vsp.AddGeom("POD", "")
wing_id = vsp.AddGeom("WING", pod_id)
vsp.SetParmVal(wing_id, "X_Rel_Location", "XForm", 2.5)
vsp.SetParmVal( wing_id, "TotalArea", "WingGeom", 25 )
vsp.SetParmVal(wing_id, "SectTess_U", "XSec_1", 12)
elev_id = vsp.AddGeom("WING", pod_id)
vsp.SetParmVal(elev_id, "X_Rel_Location", "XForm", 8)
vsp.SetParmVal(elev_id, "TotalArea", "WingGeom", 5)
rudd_id = vsp.AddGeom("WING", pod_id)
vsp.SetSetFlag(rudd_id, 3, True)
vsp.RotateSet(3, 90, 0, 0)
vsp.SetParmVal(rudd_id, "X_Rel_Location", "XForm", 8.2)
vsp.SetParmVal(rudd_id, "TotalArea", "WingGeom", 3)



# Update the vehicle before saving/exporting
vsp.Update()

# Save to a file
fname = "example_fuse.vsp3"
vsp.SetVSP3FileName(fname)
print("\tSaving vehicle file to:", fname)
vsp.WriteVSPFile(vsp.GetVSPFileName(), vsp.SET_ALL)

# Export STL
print("\tExporting mesh (STL)")
mesh_id = vsp.ExportFile("Example_Mesh.stl", vsp.SET_ALL, vsp.EXPORT_STL)
vsp.DeleteGeom(mesh_id) # Delete the mesh generated by the STL export

# Setup an Aero Analysis
"""
analysis_name = "VSPAEROSinglePoint"
print("\t",vsp.GetAnalysisDoc( analysis_name ))
analysis_method = [vsp.PANEL]
vsp.SetIntAnalysisInput(analysis_name, "AnalysisMethod", analysis_method)
# Run the Analysis
res_id = vsp.ExecAnalysis(analysis_name)
vsp.WriteResultsCSVFile( res_id, "z.csv" )
"""

"""
analysis_array = vsp.ListAnalysis()
print( "List of Available Analyses: " )
for i in range(int( len(analysis_array) )):
    print( "    " + analysis_array[i] )

    BladeElement
    CfdMeshAnalysis
    CompGeom
    CpSlicer
    DegenGeom
    EmintonLord
    FeaMeshAnalysis
    MassProp
    ParasiteDrag
    PlanarSlice
    Projection
    SurfaceIntersection
    SurfacePatches
    VSPAEROComputeGeometry
    VSPAERODegenGeom
    VSPAEROReadPreviousAnalysis
    VSPAEROSinglePoint
    VSPAEROSweep
    WaveDrag

    
https://groups.google.com/g/openvsp/c/DlsBO1x0BLw
    vsp.ListAnalysis()
Out[4]:
('BladeElement',
 'CfdMeshAnalysis',
 'CompGeom',
 'CpSlicer',
 'DegenGeom',
 'EmintonLord',
 'FeaMeshAnalysis',
 'MassProp',
 'ParasiteDrag',
 'PlanarSlice',
 'Projection',
 'SurfaceIntersection',
 'SurfacePatches',
 'VSPAEROComputeGeometry',
 'VSPAERODegenGeom',
 'VSPAEROSinglePoint',
 'VSPAEROSweep',
 'WaveDrag')

vsp.GetAnalysisInputNames('VSPAEROSinglePoint')
Out[5]:
('2DFEMFlag',
 'ActuatorDiskFlag',
 'Alpha',
 'AnalysisMethod',
 'AutoTimeNumRevs',
 'AutoTimeStepFlag',
 'BatchModeFlag',
 'Beta',
 'CGGeomSet',
 'Clmax',
 'ClmaxToggle',
 'ExperimentalInputFormatFlag',
 'FarDist',
 'FarDistToggle',
 'FixedWakeFlag',
 'FromSteadyState',
 'GeomSet',
 'GroundEffect',
 'GroundEffectToggle',
 'HoverRamp',
 'HoverRampFlag',
 'KTCorrection',
 'Mach',
 'Machref',
 'ManualVrefFlag',
 'MaxTurnAngle',
 'MaxTurnToggle',
 'NCPU',
 'NoiseCalcFlag',
 'NoiseCalcType',
 'NoiseUnits',
 'NumMassSlice',
 'NumTimeSteps',
 'NumWakeNodes',
 'Precondition',
 'ReCref',
 'ReCrefEnd',
 'ReCrefNpts',
 'RefFlag',
 'Rho',
 'RotateBladesFlag',
 'Sref',
 'Symmetry',
 'TimeStepSize',
 'UnsteadyType',
 'Vinf',
 'Vref',
 'WakeNumIter',
 'WingID',
 'Xcg',
 'Ycg',
 'Zcg',
 'bref',
 'cref')
"""
